# Generated by Django 3.1.5 on 2021-01-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100, null=True)),
                ('star_lum', models.FloatField()),
                ('star_metal', models.FloatField()),
                ('planet_eqtemp', models.FloatField()),
                ('star_efftemp', models.FloatField()),
                ('star_optmag', models.FloatField()),
                ('star_grav', models.FloatField()),
                ('star_mass', models.FloatField()),
                ('planet_rad', models.FloatField()),
                ('planet_eccen', models.FloatField()),
                ('planet_dens', models.FloatField()),
                ('planet_orbper', models.FloatField()),
                ('planet_smaxis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('saved_visuals', models.ManyToManyField(to='main_app.Visual')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.visual')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
        ),
    ]
