# Generated by Django 3.1.5 on 2021-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
